# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn global add ts-node --prefix=.
      # install deps
      - run: yarn
      # unit tests
      - run: yarn test
        env:
          CI: true
      # build UIs (note doesn't typecheck them)
      - run: yarn run build-fiddle
      - run: yarn run build-fp-ui
      # build dist (does typecheck)
      - run: yarn run build-dist
      # Percy UI tests
      # TODO: re-enable
      # - name: "Percy FP UI"
      #   uses: percy/snapshot-action@v0.1.1
      #   with:
      #     build-directory: fp/fiddle
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_FP }}
      # - name: "Percy: Generic Fiddle"
      #   uses: percy/snapshot-action@v0.1.1
      #   with:
      #     build-directory: fiddle
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_GENERIC_FIDDLE }}
